# Generated by Django 4.2.4 on 2023-08-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProfilel",
            new_name="UserProfile",
        ),
    ]
