# Generated by Django 4.2.4 on 2023-08-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_rename_name_artistprofile_artist_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="genre",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="label",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
