# Generated by Django 4.2.4 on 2023-08-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_album_genre_album_label_album_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistprofile",
            name="artist_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
