# Generated by Django 4.2.4 on 2023-08-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_rename_user_artist_artistprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="user_regular",
            new_name="user",
        ),
    ]
