# Generated by Django 4.2.4 on 2023-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_rename_user_regular_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
