# Generated by Django 4.2.4 on 2023-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_userprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
