# Generated by Django 4.2.4 on 2023-08-21 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0011_userprofile_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="wishlists",
            field=models.ManyToManyField(
                related_name="albums", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
