# Generated by Django 4.2.4 on 2023-08-25 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0015_alter_album_preview_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="buyed",
            field=models.ManyToManyField(
                related_name="album_buy", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
