# Generated by Django 4.2.4 on 2023-11-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="profiles.album",
            ),
        ),
    ]
