# Generated by Django 4.2.4 on 2023-11-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_alter_comment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
