# Generated by Django 4.2.4 on 2023-08-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="user",
        ),
        migrations.RemoveField(
            model_name="regularuser",
            name="user",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
        migrations.DeleteModel(
            name="RegularUser",
        ),
    ]
