# Generated by Django 4.2.4 on 2023-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_artist_user_remove_regularuser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="example@gmail.com", max_length=254, null=True
            ),
        ),
    ]
